spring.application.name=reminiscence

##-----data base configuration-----##

spring.datasource.url=${data_string}
#spring.datasource.username=postgres
#spring.datasource.password=postgres
# Optional: Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.write-dates-as-timestamps=false


##-----ai configuration-----##

gemini.api.key=${gemini_api_key}
groq.api.key=${groq_api_key}
siliconflow.api.key=${siliconflow_api_key}
github.models.api.key=${github_models_api_key}
#nvidia.nim.api.key=${nvidia_nim_api_key}
cloudflare.api.token=${cloudflare_api_key}
cloudflare.account.id=${cloudflare_account_id}
openrouter.api.key=${openrouter_api_key}
sambanova.api.key=${sambanova_api_key}
huggingface.api.key=${huggingface_api_key}
mistral.api.key=${mistral_api_key}

##-----authentication configuration-----##
jwt.secret=${jwt_screte}
jwt.expiration=2592000000

#mail config
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${email}
#spring.mail.password=${email_app_password}
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

##-----mail service-----##
brevo.api.key=${brevo_api_key}

firebase.project.id=${FIREBASE_PROJECT_ID}
firebase.private.key.id=${FIREBASE_PRIVATE_KEY_ID}
firebase.private.key=${FIREBASE_PRIVATE_KEY}
firebase.client.email=${FIREBASE_CLIENT_EMAIL}