spring.application.name=reminiscence


spring.datasource.url=${data_string}
#spring.datasource.username=postgres
#spring.datasource.password=postgres
# Optional: Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.write-dates-as-timestamps=false
gemini.api.key=${gemini_api_key}
groq.api.key=${groq_api_key}

resend.api.key=${resend_api_key}

jwt.secret=${jwt_screte}
jwt.expiration=86400000

#mail config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${email}
spring.mail.password=${email_app_password}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true